#!/usr/bin/env python3
"""Bootstrap the two disposable vstart clusters used by exercise.py.

Both nodes run MON=1 OSD=1 MGR=1 RGW=1 ../src/vstart.sh -n
--without-dashboard, with MDS=0 FS=0 to focus this lab on RGW. An explicit
setup --reset is required for the first start and every destructive reset.
vstart -n replaces build-directory cluster data; vstart's reset/stop paths
can also stop other Ceph processes belonging to the invoking user.

Importing this module or calling Lab.load() never starts a daemon. Dependencies
are installed only into the local build/.venv-rgw-repro virtual environment.
The private JSON state is the interface shared with the separate exercise.
"""

from __future__ import annotations

import argparse
import contextlib
import datetime
import fcntl
import json
import os
from pathlib import Path
import re
import secrets
import shlex
import signal
import subprocess
import sys
import tempfile
import time
import uuid


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_DIR = SCRIPT_DIR.parents[3]
BUILD_DIR = REPO_DIR / "build"
DEFAULT_CONFIG = BUILD_DIR / "rgw-repro" / "state.json"
REMOTE_HOST = "root@172.31.139.22"
REMOTE_CONTAINER = "ceph-dev"
ENDPOINTS = {
    "zone1": "http://172.31.139.21:8000",
    "zone2": "http://172.31.139.22:8000",
}
ZONES = ("zone1", "zone2")
OWNER = "multisite_migration_repro"
EXPECTED_BASE_COMMIT = "10cef5efe60f078b70208ec17f03305a8dcc4100"
START_TIMEOUT = 300
STOP_TIMEOUT = 30
LOG_LIMIT = 128 * 1024


class LabError(RuntimeError):
    """An actionable error whose message contains no credential-bearing argv."""


def redact(text, credentials=()):
    """Redact both lab credentials and credentials generated by vstart."""
    text = str(text or "")
    for value in sorted(set(credentials), key=len, reverse=True):
        if value:
            text = text.replace(value, "<redacted>")
    text = re.sub(
        r'(?i)("(?:access_key|secret_key|secret|token|authorization)"\s*:\s*)'
        r'"(?:\\.|[^"\\])*"',
        r'\1"<redacted>"', text,
    )
    text = re.sub(
        r"(?im)((?:--)?(?:access[-_]key|secret(?:[-_]key)?|aws_access_key_id|"
        r"aws_secret_access_key|AWSAccessKeyId)\s*=\s*)([^\s,]+)",
        r"\1<redacted>", text,
    )
    text = re.sub(
        r'''(?i)(--(?:access[-_]key|secret(?:[-_]key)?)\s+)("[^"\n]*"|'[^'\n]*'|\S+)''',
        r"\1<redacted>", text,
    )
    text = re.sub(r"(?im)(authorization\s*[:=]\s*)[^\r\n]+",
                  r"\1<redacted>", text)
    text = re.sub(r"(?im)^(\s*key\s*=\s*)[^\r\n]+", r"\1<redacted>", text)
    text = re.sub(r"(?im)^(\s*(?:access|secret)\s+key:\s*)\S+",
                  r"\1<redacted>", text)
    return re.sub(r"(?i)(https?://)[^/\s@]+@", r"\1<redacted>@", text)


def private_directory(path):
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    path.chmod(0o700)
    return path


def private_write(path, text):
    """Atomically write state/diagnostics without a world-readable interval."""
    path = Path(path)
    private_directory(path.parent)
    fd, temporary = tempfile.mkstemp(prefix="." + path.name + ".", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as output:
            os.fchmod(output.fileno(), 0o600)
            output.write(text)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
        path.chmod(0o600)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def timestamp():
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


class CommandError(subprocess.CalledProcessError):
    def __init__(self, node, result):
        super().__init__(result.returncode, "<redacted command>",
                         output=node.redact(result.stdout),
                         stderr=node.redact(result.stderr))
        self.node_name = node.name

    def __str__(self):
        return "{}: command failed (exit {}); see bootstrap.log".format(
            self.node_name, self.returncode)


class CommandTimeout(subprocess.TimeoutExpired):
    def __init__(self, node, timeout):
        super().__init__("<redacted command>", timeout)
        self.node_name = node.name

    def __str__(self):
        return "{}: command timed out after {} seconds; see bootstrap.log".format(
            self.node_name, self.timeout)


# The remote shell receives all paths and commands as positional arguments.
# shlex.join() additionally quotes the entire docker invocation for SSH.
REMOTE_ENV = r'''
build=$1
shift
export CEPH_DEV=1 CEPH_CONF="$build/ceph.conf" CEPH_KEYRING="$build/keyring"
export PATH="$build/bin:$PATH"
export LD_LIBRARY_PATH="$build/lib:$build/external/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH="$build/../src/pybind:$build/../src/python-common:$build/lib/cython_modules/lib.3${PYTHONPATH:+:$PYTHONPATH}"
exec "$@"
'''


class Node:
    """Run captured, noninteractive commands in a local or remote build tree."""

    def __init__(self, name, build_dir, remote_host=None, container=None,
                 credentials=(), logger=None, local_workdir=BUILD_DIR):
        self.name = name
        self.build_dir = Path(build_dir)
        self.remote_host = remote_host
        self.container = container
        self.credentials = tuple(credentials)
        self.logger = logger
        self.local_workdir = Path(local_workdir)
        if not self.build_dir.is_absolute():
            raise LabError("Node build directories must be absolute")
        if remote_host and not re.fullmatch(r"[\w.-]+@[\w.:-]+", remote_host):
            raise LabError("Invalid SSH host; use user@host")
        if remote_host and not re.fullmatch(r"[\w][\w.-]*", container or ""):
            raise LabError("Invalid Docker container name")

    @property
    def conf(self):
        return str(self.build_dir / "ceph.conf")

    def redact(self, text):
        return redact(text, self.credentials)

    def _record(self, message):
        if self.logger:
            self.logger("{}: {}".format(self.name, self.redact(message)))

    def run(self, argv, timeout=120, check=True, input=None):
        """Return CompletedProcess with text stdout/stderr; never print argv.

        check=True raises credential-redacted CalledProcessError/TimeoutExpired
        subclasses. A remote timeout runs inside Docker as well as on SSH.
        """
        argv = [os.fspath(arg) for arg in argv]
        if not argv or timeout <= 0:
            raise LabError("A command and a positive timeout are required")
        env = os.environ.copy()
        if self.remote_host:
            bounded = ["timeout", "--signal=TERM", "--kill-after=5s",
                       str(timeout) + "s", *argv]
            docker = ["docker", "exec", "-i", "-w", str(self.build_dir),
                      self.container, "bash", "-c", REMOTE_ENV, "rgw-repro",
                      str(self.build_dir), *bounded]
            command = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10"]
            control_path = env.get("RGW_REPRO_SSH_CONTROL_PATH")
            if control_path:
                if not Path(control_path).is_absolute():
                    raise LabError("SSH control socket path must be absolute")
                # Reuse an explicitly established connection, without retrying
                # or replaying a potentially mutating remote command.
                command.extend(["-o", "ControlMaster=no", "-o", "ControlPath=" + control_path])
            command.extend(["--", self.remote_host, shlex.join(docker)])
            # The remote deadline must expire before the SSH-side deadline.
            process_timeout = timeout + 15
        else:
            env.update(CEPH_DEV="1", CEPH_CONF=self.conf,
                       CEPH_KEYRING=str(self.build_dir / "keyring"))
            prefixes = {
                "PATH": [self.build_dir / "bin"],
                "LD_LIBRARY_PATH": [self.build_dir / "lib",
                                    self.build_dir / "external/lib"],
                "PYTHONPATH": [self.build_dir.parent / "src/pybind",
                               self.build_dir.parent / "src/python-common",
                               self.build_dir / "lib/cython_modules/lib.3"],
            }
            for key, paths in prefixes.items():
                env[key] = os.pathsep.join([*(str(p) for p in paths),
                                           *([env[key]] if env.get(key) else [])])
            command = argv
            process_timeout = timeout
        # Only the executable is logged: arguments may contain system keys.
        self._record("running {} (timeout={}s)".format(Path(argv[0]).name, timeout))
        try:
            process = subprocess.Popen(
                command, cwd=self.local_workdir if self.remote_host else self.build_dir,
                env=env, stdin=subprocess.PIPE if input is not None else subprocess.DEVNULL,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                start_new_session=True,
            )
        except OSError:
            self._record("could not launch command")
            raise LabError("{}: could not launch command in its build directory".format(
                self.name)) from None
        try:
            stdout, stderr = process.communicate(input=input, timeout=process_timeout)
        except subprocess.TimeoutExpired:
            with contextlib.suppress(ProcessLookupError):
                os.killpg(process.pid, signal.SIGKILL)
            # A descendant may still hold a pipe. Bound cleanup too.
            try:
                stdout, stderr = process.communicate(timeout=5)
                self._record(self.redact(stdout + "\n" + stderr)[:LOG_LIMIT])
            except subprocess.TimeoutExpired:
                process.stdout.close()
                process.stderr.close()
                with contextlib.suppress(subprocess.TimeoutExpired):
                    process.wait(timeout=5)
            self._record("command deadline expired")
            raise CommandTimeout(self, timeout) from None
        except BaseException:
            with contextlib.suppress(ProcessLookupError):
                os.killpg(process.pid, signal.SIGKILL)
            process.stdout.close()
            process.stderr.close()
            with contextlib.suppress(subprocess.TimeoutExpired):
                process.wait(timeout=5)
            raise
        result = subprocess.CompletedProcess(argv, process.returncode, stdout, stderr)
        for stream, text in (("stdout", stdout), ("stderr", stderr)):
            safe = self.redact(text)
            if safe:
                self._record("{}:\n{}{}".format(
                    stream, safe[:LOG_LIMIT],
                    "\n[diagnostic output truncated]" if len(safe) > LOG_LIMIT else ""))
        self._record("exit {}".format(result.returncode))
        if self.remote_host and result.returncode == 124:
            raise CommandTimeout(self, timeout)
        if check and result.returncode:
            raise CommandError(self, result)
        return result


# Only the PID recorded for this build/entity is touched. Matching executable,
# configuration, entity, and (for RGW) explicit pid-file are mandatory. Linux
# starttime protects against signalling a PID reused while waiting for exit.
PID_CONTROL = r'''
import json, os, pathlib, signal, sys, time
build, binary, entity, pidfile, action, seconds = sys.argv[1:]
pidfile = pathlib.Path(pidfile)
try:
    pid = int(pidfile.read_text().strip())
except FileNotFoundError:
    if action == "stop":
        sys.exit(0)
    sys.exit("configured daemon PID file is missing")
except ValueError:
    sys.exit("invalid configured daemon PID file")
if pid <= 1:
    sys.exit("invalid daemon PID")
proc = pathlib.Path("/proc") / str(pid)
def identity():
    try:
        stat = (proc / "stat").read_text().rsplit(")", 1)[1].split()
        if stat[0] == "Z":
            return None
        return stat[19]
    except FileNotFoundError:
        return None
started = identity()
if started is None:
    if action == "stop":
        pidfile.unlink(missing_ok=True)
        sys.exit(0)
    sys.exit("configured daemon is not running")
args = (proc / "cmdline").read_bytes().decode().split("\0")[:-1]
def option(*names):
    for i, arg in enumerate(args):
        for name in names:
            if arg == name and i + 1 < len(args):
                return args[i + 1]
            if arg.startswith(name + "="):
                return arg.split("=", 1)[1]
    return None
if pathlib.Path(args[0]).name != binary:
    sys.exit("PID belongs to another executable; refusing to signal")
if option("-c", "--conf") != str(pathlib.Path(build) / "ceph.conf"):
    sys.exit("PID belongs to another configuration; refusing to signal")
if option("-n", "--name") != entity and option("-i", "--id") != entity.split(".")[-1]:
    sys.exit("PID belongs to another entity; refusing to signal")
if binary == "radosgw" and option("--pid-file", "--pid_file") != str(pidfile):
    sys.exit("RGW PID file does not match command line; refusing to signal")
if action == "check":
    print(json.dumps({"pid": pid, "entity": entity}))
    sys.exit(0)
def alive():
    return identity() == started
if alive():
    os.kill(pid, signal.SIGTERM)
deadline = time.monotonic() + float(seconds)
while alive() and time.monotonic() < deadline:
    time.sleep(0.2)
if alive():
    os.kill(pid, signal.SIGKILL)
    deadline = time.monotonic() + 5
    while alive() and time.monotonic() < deadline:
        time.sleep(0.2)
if alive():
    sys.exit("daemon did not exit before the restart deadline")
if pidfile.exists() and pidfile.read_text().strip() == str(pid):
    pidfile.unlink()
'''

HTTP_PROBE = r'''
import sys, urllib.error, urllib.request
opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
try:
    with opener.open(sys.argv[1], timeout=float(sys.argv[2])) as response:
        code = response.status
except urllib.error.HTTPError as error:
    code = error.code
if code not in (200, 403, 405):
    sys.exit("unexpected RGW HTTP status " + str(code))
print("HTTP " + str(code))
'''


def wait_for(label, probe, timeout):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        remaining = deadline - time.monotonic()
        try:
            if probe(max(0.1, min(10, remaining))):
                return
        except (LabError, subprocess.SubprocessError, ValueError, KeyError):
            pass
        time.sleep(min(1, max(0, deadline - time.monotonic())))
    raise LabError("Timed out waiting for {} ({} seconds); see bootstrap.log".format(
        label, timeout))


def parse_json(result, label):
    try:
        value = json.loads(result.stdout)
    except (ValueError, TypeError):
        raise LabError("{} returned invalid JSON; see bootstrap.log".format(label)) from None
    if not isinstance(value, dict):
        raise LabError("{} returned an unexpected JSON value".format(label))
    return value


class Lab:
    """Private state plus the admin/Node API consumed by exercise.py."""

    def __init__(self, config, path=DEFAULT_CONFIG):
        self.config = config
        self.path = Path(path)
        self.artifact_dir = Path(config["artifact_dir"])
        credentials = []
        for key in ("user", "system"):
            for name in ("access_key", "secret_key"):
                value = config.get(key, {}).get(name)
                if value:
                    credentials.append(value)
        self.credentials = tuple(credentials)
        self.nodes = {
            "zone1": Node("zone1", config["build_dir"], credentials=credentials,
                          logger=self.log),
            "zone2": Node("zone2", config["remote_build_dir"], config["remote_host"],
                          config["remote_container"], credentials, self.log,
                          local_workdir=config["build_dir"]),
        }

    @classmethod
    def load(cls, path=DEFAULT_CONFIG):
        """Read owned state without starting, resetting, or installing anything."""
        path = Path(path)
        try:
            config = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            raise LabError("Cannot read lab state at {}; run setup --reset".format(path)) from None
        if not isinstance(config, dict) or config.get("owner") != OWNER or config.get("schema_version") != 1:
            raise LabError("State is not owned by this lab; refusing to reuse it")
        required = ("realm", "zonegroup", "build_dir", "remote_host", "remote_container",
                    "remote_build_dir", "endpoints", "user", "artifact_dir", "fsids")
        if any(key not in config for key in required):
            raise LabError("Lab state is incomplete; run setup --reset")
        if any(not isinstance(config[key], dict) for key in ("endpoints", "user", "fsids")):
            raise LabError("Lab state contains invalid endpoint, user, or FSID records")
        if any(not isinstance(config[key], str) or not config[key] for key in
               ("realm", "zonegroup", "build_dir", "remote_host", "remote_container",
                "remote_build_dir", "artifact_dir")):
            raise LabError("Lab state contains invalid node configuration")
        for zone in ZONES:
            cls._validate_endpoint(config["endpoints"].get(zone, ""))
        if any(not config["user"].get(key) for key in ("uid", "access_key", "secret_key")):
            raise LabError("Lab state has no ordinary S3 user credentials")
        return cls(config, path)

    @staticmethod
    def _validate_endpoint(endpoint):
        from urllib.parse import urlsplit
        try:
            parsed = urlsplit(endpoint)
            valid = (parsed.scheme == "http" and parsed.hostname and parsed.port == 8000
                     and not parsed.username and not parsed.password
                     and parsed.path in ("", "/") and not parsed.query and not parsed.fragment)
        except (TypeError, ValueError):
            valid = False
        if not valid:
            raise LabError("Lab endpoints must be credential-free HTTP URLs on port 8000")

    def redact(self, text):
        return redact(text, self.credentials)

    def log(self, message):
        private_directory(self.artifact_dir)
        path = self.artifact_dir / "bootstrap.log"
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as output:
            os.fchmod(output.fileno(), 0o600)
            output.write("{} {}\n".format(timestamp(), self.redact(message)))

    def save(self):
        private_write(self.path, json.dumps(self.config, indent=2) + "\n")

    def admin(self, zone, *args, check=True, timeout=120):
        node = self.nodes[zone]
        return node.run([str(node.build_dir / "bin/radosgw-admin"), "-c", node.conf,
                         "--rgw-zone", zone, "--rgw-realm", self.config["realm"],
                         "--rgw-zonegroup", self.config["zonegroup"], *args],
                        timeout=timeout, check=check)

    def _raw_admin(self, zone, *args, timeout=120):
        node = self.nodes[zone]
        return node.run([str(node.build_dir / "bin/radosgw-admin"), "-c", node.conf,
                         *args], timeout=timeout)

    def _ceph(self, zone, *args, timeout=120, check=True):
        node = self.nodes[zone]
        return node.run([str(node.build_dir / "bin/ceph"), "-c", node.conf,
                         "-k", str(node.build_dir / "keyring"), *args],
                        timeout=timeout, check=check)

    def versions(self):
        versions = {}
        commits = set()
        for zone, node in self.nodes.items():
            source = str(node.build_dir.parent)
            result = node.run(["git", "-C", source, "rev-parse", "HEAD"], timeout=30)
            head = result.stdout.strip().lower()
            versions[zone] = {}
            for binary in ("ceph", "radosgw"):
                result = node.run([str(node.build_dir / "bin" / binary), "--version"],
                                  timeout=30)
                match = re.search(r"\(([0-9a-fA-F]{40})\)", result.stdout)
                if not match:
                    raise LabError("{} {} did not report its compiled commit".format(zone, binary))
                commit = match.group(1).lower()
                if commit != head:
                    raise LabError("{} {} compiled commit does not match its checkout HEAD".format(
                        zone, binary))
                commits.add(commit)
                versions[zone][binary] = {"commit": commit, "version": result.stdout.strip()}
            ancestry = node.run(["git", "-C", source, "merge-base", "--is-ancestor",
                                 EXPECTED_BASE_COMMIT, head], timeout=30, check=False)
            if ancestry.returncode == 1:
                raise LabError("{} checkout HEAD does not descend from base {}".format(
                    zone, EXPECTED_BASE_COMMIT))
            if ancestry.returncode:
                raise CommandError(node, ancestry)
        if len(commits) != 1:
            raise LabError("Local/remote ceph and radosgw binary commits do not match")
        return versions

    def fsid(self, zone, live=True):
        node = self.nodes[zone]
        if live:
            result = self._ceph(zone, "fsid", timeout=15)
        else:
            result = node.run([str(node.build_dir / "bin/ceph-conf"), "-c", node.conf,
                               "--lookup", "fsid"], timeout=15)
        try:
            return str(uuid.UUID(result.stdout.strip()))
        except ValueError:
            raise LabError("{} has no valid cluster FSID".format(zone)) from None

    def check_fsids(self, live=True, complete=True):
        recorded = self.config["fsids"]
        if complete and set(recorded) != set(ZONES):
            raise LabError("State lacks both owned cluster FSIDs; run setup --reset")
        found = {}
        for zone in ZONES:
            if zone in recorded:
                found[zone] = self.fsid(zone, live=live)
                if found[zone] != recorded[zone]:
                    raise LabError("{} FSID does not match owned state; refusing to reuse/reset".format(zone))
        if len(found) == 2 and found["zone1"] == found["zone2"]:
            raise LabError("The two vstart clusters must have distinct FSIDs")

    def _pid(self, zone, binary="radosgw", entity="client.rgw.8000", action="check"):
        node = self.nodes[zone]
        filename = "radosgw.8000.pid" if binary == "radosgw" else entity + ".pid"
        return node.run(["python3", "-c", PID_CONTROL, str(node.build_dir), binary,
                         entity, str(node.build_dir / "out" / filename), action,
                         str(STOP_TIMEOUT)], timeout=STOP_TIMEOUT + 15)

    def stop_for_reset(self):
        # Used only after the caller explicitly supplies --reset.
        for zone in ZONES:
            for binary, entity in (("radosgw", "client.rgw.8000"),
                                   ("ceph-mgr", "mgr.x"), ("ceph-osd", "osd.0"),
                                   ("ceph-mon", "mon.a")):
                self._pid(zone, binary, entity, action="stop")

    def http_ready(self, source, destination, timeout):
        result = self.nodes[source].run(
            ["python3", "-c", HTTP_PROBE, self.config["endpoints"][destination],
             str(min(5, timeout))], timeout=timeout, check=False)
        return result.returncode == 0

    def check_http(self, timeout):
        for source in ZONES:
            for destination in ZONES:
                wait_for("{} -> {} HTTP endpoint".format(source, destination),
                         lambda remaining, s=source, d=destination:
                         self.http_ready(s, d, remaining), timeout)

    def start_vstart(self, zone, timeout):
        node = self.nodes[zone]
        # Pin vstart's aliases and paths even if the caller sourced another lab.
        environment = {
            "MON": "1", "OSD": "1", "MGR": "1", "RGW": "1", "MDS": "0", "FS": "0",
            "CEPH_NUM_MON": "1", "CEPH_NUM_OSD": "1", "CEPH_NUM_MGR": "1",
            "CEPH_NUM_RGW": "1", "CEPH_NUM_MDS": "0", "CEPH_NUM_FS": "0",
            "NFS": "0", "GANESHA_DAEMON_NUM": "0", "CEPH_RGW_PORT": "8000",
            "CEPH_DIR": str(node.build_dir), "CEPH_CONF_PATH": str(node.build_dir),
            "CEPH_DEV_DIR": str(node.build_dir / "dev"),
            "CEPH_OUT_DIR": str(node.build_dir / "out"),
            "CEPH_ASOK_DIR": str(node.build_dir / "asok"),
            "CEPH_BIN": str(node.build_dir / "bin"),
            "CEPH_LIB": str(node.build_dir / "lib"),
            "CEPH_ADM": str(node.build_dir / "bin/ceph"),
        }
        node.run(["timeout", "--signal=TERM", "--kill-after=5s", str(timeout) + "s",
                  "env", "-u", "VSTART_DEST", "-u", "CEPH_BUILD_ROOT",
                  "-u", "CEPH_KEYRING",
                  *(key + "=" + value for key, value in environment.items()),
                  "../src/vstart.sh", "-n", "--without-dashboard"], timeout=timeout + 15)
        wait_for("{} monitor/OSD/MGR readiness".format(zone),
                 lambda remaining: self._cluster_ready(zone, remaining), timeout)
        configured = self.fsid(zone, live=False)
        if self.fsid(zone) != configured:
            raise LabError("{} live/configured FSIDs differ".format(zone))
        self.config["fsids"][zone] = configured
        self.save()
        self._pid(zone)
        wait_for("{} initial RGW".format(zone),
                 lambda remaining: self.http_ready(zone, zone, remaining), timeout)

    def _cluster_ready(self, zone, timeout):
        result = self._ceph(zone, "status", "--format=json", timeout=timeout, check=False)
        if result.returncode:
            return False
        status = parse_json(result, "ceph status")
        osds = status.get("osdmap", {})
        # Older releases nest the OSD map one level deeper.
        osds = osds.get("osdmap", osds)
        return (osds.get("num_up_osds", 0) == 1 and osds.get("num_in_osds", 0) == 1
                and status.get("mgrmap", {}).get("available") is True
                and bool(status.get("quorum")))

    def gateway_settings(self, zone):
        # These names are verified in src/common/options/rgw.yaml.in. Also check
        # the running build's option schema before setting maintenance flags.
        options = {"debug_rgw": "20", "rgw_dynamic_resharding": "false",
                   "rgw_enable_lc_threads": "false"}
        for key, value in options.items():
            result = self._ceph(zone, "config", "help", key, "--format=json", check=False)
            if result.returncode:
                if key == "rgw_enable_lc_threads":
                    self.log("{}: LC thread option unavailable; keeping its default".format(zone))
                    continue
                raise LabError("{} required gateway option {} is unavailable".format(zone, key))
            self._ceph(zone, "config", "set", "client.rgw.8000", key, value)

    def restart_gateway(self, zone, timeout):
        node = self.nodes[zone]
        self._pid(zone, action="stop")
        out = node.build_dir / "out"
        node.run([str(node.build_dir / "bin/radosgw"), "-c", node.conf,
                  "-n", "client.rgw.8000", "--rgw-realm", self.config["realm"],
                  "--rgw-zonegroup", self.config["zonegroup"], "--rgw-zone", zone,
                  "--log-file=" + str(out / "radosgw.8000.log"),
                  "--admin-socket=" + str(out / "radosgw.8000.asok"),
                  "--pid-file=" + str(out / "radosgw.8000.pid"),
                  "--rgw_luarocks_location=" + str(out / "luarocks"),
                  "--rgw_frontends=beast port=8000", "--debug-rgw=20",
                  "--rgw-dynamic-resharding=false"], timeout=timeout)
        wait_for("{} restarted RGW".format(zone),
                 lambda remaining: self.http_ready(zone, zone, remaining), timeout)
        self._pid(zone)

    def configure_multisite(self, timeout):
        realm, group = self.config["realm"], self.config["zonegroup"]
        system = self.config["system"]
        keys = ["--access-key", system["access_key"], "--secret", system["secret_key"]]
        self._raw_admin("zone1", "realm", "create", "--rgw-realm", realm, "--default")
        self._raw_admin("zone1", "zonegroup", "create", "--rgw-realm", realm,
                        "--rgw-zonegroup", group, "--master", "--default",
                        "--endpoints", self.config["endpoints"]["zone1"])
        self._raw_admin("zone1", "zone", "create", "--rgw-realm", realm,
                        "--rgw-zonegroup", group, "--rgw-zone", "zone1", "--master",
                        "--default", "--read-only=false", "--sync-from-all=true",
                        "--endpoints", self.config["endpoints"]["zone1"], *keys)
        self.admin("zone1", "user", "create", "--uid", system["uid"],
                   "--display-name", "Migration repro system user", "--system", *keys)
        self.admin("zone1", "period", "update", "--commit")
        self.restart_gateway("zone1", timeout)
        self._raw_admin("zone2", "realm", "pull", "--url", self.config["endpoints"]["zone1"],
                        "--rgw-realm", realm, "--default", *keys)
        self._raw_admin("zone2", "zonegroup", "default", "--rgw-realm", realm,
                        "--rgw-zonegroup", group)
        self._raw_admin("zone2", "zone", "create", "--rgw-realm", realm,
                        "--rgw-zonegroup", group, "--rgw-zone", "zone2", "--default",
                        "--read-only=false", "--sync-from-all=true",
                        "--endpoints", self.config["endpoints"]["zone2"], *keys)
        self.admin("zone2", "period", "update", "--commit", timeout=timeout)
        # Restart both against the final committed, two-member period.
        for zone in ZONES:
            self.restart_gateway(zone, timeout)

    def topology(self):
        states = []
        for zone in ZONES:
            realm = parse_json(self.admin(zone, "realm", "get"), "realm get")
            period = parse_json(self.admin(zone, "period", "get"), "period get")
            group = parse_json(self.admin(zone, "zonegroup", "get"), "zonegroup get")
            groups = period.get("period_map", {}).get("zonegroups", [])
            matches = [g for g in groups if g.get("name") == self.config["zonegroup"]]
            if len(matches) != 1 or matches[0] != group:
                raise LabError("{} zonegroup does not match its committed period".format(zone))
            members = {z["name"]: z for z in group.get("zones", [])}
            if (set(members) != set(ZONES) or group.get("is_master") is not True
                    or group.get("master_zone") != members["zone1"]["id"]):
                raise LabError("{} period has unexpected masters or zone membership".format(zone))
            for name, member in members.items():
                if (member.get("log_data") is not True or member.get("sync_from_all") is not True
                        or member.get("read_only") is not False
                        or member.get("endpoints") != [self.config["endpoints"][name]]):
                    raise LabError("{} is not a read-write, bi-directional logged zone".format(name))
            if (realm.get("current_period") != period.get("id")
                    or period.get("realm_id") != realm.get("id")
                    or period.get("master_zone") != members["zone1"]["id"]):
                raise LabError("{} realm/period identifiers do not agree".format(zone))
            states.append({"realm_id": realm["id"], "period_id": period["id"],
                           "period_epoch": period["epoch"], "zonegroup_id": group["id"],
                           "zone_ids": {name: members[name]["id"] for name in ZONES}})
        if states[0] != states[1]:
            raise LabError("The two zones do not share the same committed period")
        return states[0]

    def user_ready(self, zone, timeout):
        user = self.config["user"]
        result = self.admin(zone, "user", "info", "--uid", user["uid"],
                            timeout=timeout, check=False)
        if result.returncode:
            return False
        info = parse_json(result, "user info")
        return (info.get("user_id") == user["uid"]
                and info.get("system", False) in (False, 0, "false")
                and info.get("admin", False) in (False, 0, "false")
                and info.get("suspended", 0) in (False, 0)
                and any(key.get("access_key") == user["access_key"]
                        and key.get("secret_key") == user["secret_key"]
                        for key in info.get("keys", [])))

    def check_user(self, timeout):
        for zone in ZONES:
            wait_for("{} ordinary S3 user metadata and credentials".format(zone),
                     lambda remaining, z=zone: self.user_ready(z, remaining), timeout)

    def validate(self, timeout):
        self.check_fsids(live=False)
        self.check_fsids()
        versions = self.versions()
        if versions != self.config.get("versions"):
            raise LabError("Compiled binary versions differ from the saved lab state")
        for zone in ZONES:
            self._pid(zone)
            wait_for("{} existing cluster readiness".format(zone),
                     lambda remaining, z=zone: self._cluster_ready(z, remaining), timeout)
        self.check_http(timeout)
        if self.topology() != self.config.get("topology"):
            raise LabError("Committed multisite topology differs from the saved lab state")
        self.check_user(timeout)

    def ensure_venv(self):
        venv = Path(self.config["build_dir"]) / ".venv-rgw-repro"
        python = venv / "bin/python"
        node = self.nodes["zone1"]
        if not python.exists():
            node.run([sys.executable, "-m", "venv", str(venv)], timeout=120)
        node.run([str(python), "-m", "pip", "install", "--disable-pip-version-check",
                  "-r", str(SCRIPT_DIR / "requirements.txt")], timeout=600)
        return python

    def run_exercise(self, objects, timeout):
        exercise = SCRIPT_DIR / "exercise.py"
        if not exercise.is_file():
            raise LabError("exercise.py has not yet been supplied by the parent")
        python = self.ensure_venv()
        result = self.nodes["zone1"].run(
            [str(python), str(exercise), "--config", str(self.path),
             "--objects", str(objects), "--timeout", str(timeout)],
            timeout=max(1800, timeout * 40), check=False)
        # Exercise output can contain request/admin diagnostics: redact it too.
        sys.stdout.write(self.redact(result.stdout))
        sys.stderr.write(self.redact(result.stderr))
        return result.returncode

    def collect_logs(self, output=None):
        stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%S.%fZ")
        output = private_directory(output or self.artifact_dir / ("logs-" + stamp))
        for zone, node in self.nodes.items():
            commands = {
                "ceph-status": lambda: self._ceph(zone, "status", "--format=json", check=False, timeout=30),
                "ceph-health": lambda: self._ceph(zone, "health", "detail", check=False, timeout=30),
                "rgw-sync-status": lambda: self.admin(zone, "sync", "status", check=False, timeout=30),
                "metadata-sync-status": lambda: self.admin(zone, "metadata", "sync", "status", check=False, timeout=30),
                "radosgw.8000.log": lambda: node.run([
                    "python3", "-c",
                    "import pathlib,sys; p=pathlib.Path(sys.argv[1]); "
                    "f=p.open('rb'); size=f.seek(0,2); start=max(0,size-8*1024*1024); "
                    "f.seek(start); print('[last 8 MiB; earlier log omitted]' if start else ''); "
                    "sys.stdout.write(f.read().decode('utf-8',errors='replace'))",
                    str(node.build_dir / "out/radosgw.8000.log")], timeout=30, check=False),
            }
            for name, command in commands.items():
                try:
                    result = command()
                    text = "exit={}\n{}\n{}".format(result.returncode, result.stdout, result.stderr)
                except (LabError, subprocess.SubprocessError) as error:
                    text = str(error) + "\n"
                private_write(output / (zone + "-" + name + ".txt"), self.redact(text))
        # This deliberately excludes private state.json and keyrings.
        private_write(output / "summary.json", json.dumps({
            "collected_at": timestamp(), "endpoints": self.config["endpoints"],
            "fsids": self.config["fsids"], "versions": self.config.get("versions"),
            "topology": self.config.get("topology"),
        }, indent=2) + "\n")
        return output


def new_config(args):
    build = args.build_dir.resolve()
    if not build.is_dir():
        raise LabError("Local build directory does not exist")
    endpoints = {"zone1": args.zone1_endpoint, "zone2": args.zone2_endpoint}
    for endpoint in endpoints.values():
        Lab._validate_endpoint(endpoint)
    if endpoints["zone1"] == endpoints["zone2"]:
        raise LabError("The two zones need distinct HTTP endpoints")

    def credentials(uid):
        return {"uid": uid, "access_key": secrets.token_hex(10).upper(),
                "secret_key": secrets.token_hex(20)}

    return {
        "owner": OWNER, "schema_version": 1, "lab_id": str(uuid.uuid4()),
        "created_at": timestamp(), "status": "bootstrapping",
        "realm": "migration-repro", "zonegroup": "migration-repro",
        "build_dir": str(build), "remote_host": args.remote_host,
        "remote_container": args.remote_container,
        "remote_build_dir": str(args.remote_build_dir), "endpoints": endpoints,
        "artifact_dir": str(build / "rgw-repro"),
        "user": credentials("migration-repro"),
        "system": credentials("migration-repro-system"), "fsids": {},
    }


@contextlib.contextmanager
def setup_lock(path):
    path = Path(path)
    private_directory(path.parent)
    fd = os.open(str(path) + ".setup.lock", os.O_CREAT | os.O_RDWR, 0o600)
    with os.fdopen(fd, "w") as lock:
        os.fchmod(lock.fileno(), 0o600)
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            raise LabError("Another setup is already using this state file") from None
        yield


def setup(args):
    path = args.config.resolve()
    with setup_lock(path):
        previous = Lab.load(path) if path.exists() else None
        if not args.reset:
            if previous is None:
                raise LabError("No owned lab state exists; the first setup requires --reset")
            if previous.config.get("status") != "ready":
                raise LabError("The prior bootstrap is incomplete; retry with setup --reset")
            previous.validate(args.timeout)
            lab = previous
        else:
            config = new_config(args)
            lab = Lab(config, path)
            # Reject reset against changed targets or mismatched FSIDs before
            # stopping any daemon. Incomplete state still protects known FSIDs.
            if previous:
                for key in ("build_dir", "remote_host", "remote_container", "remote_build_dir"):
                    if previous.config[key] != config[key]:
                        raise LabError("Reset targets differ from owned state ({})".format(key))
                previous.check_fsids(live=False, complete=False)
            config["versions"] = lab.versions()
            lab.ensure_venv()
            print("Resetting disposable vstart data on both nodes. vstart reset/stop "
                  "paths can stop other Ceph processes owned by the invoking user.", file=sys.stderr)
            lab.log("Explicit --reset: starting a new two-cluster lab")
            lab.stop_for_reset()
            lab.save()
            try:
                for zone in ZONES:
                    lab.start_vstart(zone, args.start_timeout)
                    lab.gateway_settings(zone)
                lab.check_fsids()
                lab.check_http(args.timeout)
                lab.configure_multisite(args.start_timeout)
                lab.check_http(args.timeout)
                config["topology"] = lab.topology()
                user = config["user"]
                lab.admin("zone1", "user", "create", "--uid", user["uid"],
                          "--display-name", "Migration repro S3 user",
                          "--access-key", user["access_key"], "--secret", user["secret_key"])
                lab.check_user(args.timeout)
                config["status"] = "ready"
                config["ready_at"] = timestamp()
                lab.save()
            except (LabError, subprocess.SubprocessError, OSError, ValueError, KeyError):
                lab.log("Bootstrap failed; private state retained for investigation/reset")
                with contextlib.suppress(LabError, subprocess.SubprocessError, OSError):
                    lab.collect_logs()
                raise
        print("Lab ready; private config: {}".format(path))
        if args.run:
            return lab.run_exercise(args.objects, args.timeout)
    return 0


def positive_int(value):
    try:
        parsed = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError("must be a positive integer") from None
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def parser():
    result = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    result.add_argument("--config", type=Path, default=DEFAULT_CONFIG,
                        help="private lab state JSON (default: %(default)s)")
    commands = result.add_subparsers(dest="command", required=True)
    start = commands.add_parser("setup", help="bootstrap or validate the two-cluster lab")
    start.add_argument("--reset", action="store_true", help="explicitly replace disposable vstart clusters")
    start.add_argument("--run", action="store_true", help="run the separate exercise in the local virtualenv")
    start.add_argument("--objects", type=positive_int, default=3)
    start.add_argument("--timeout", type=positive_int, default=90, help="readiness/exercise timeout (seconds)")
    start.add_argument("--start-timeout", type=positive_int, default=START_TIMEOUT,
                       help="vstart and gateway restart timeout (seconds)")
    start.add_argument("--build-dir", type=Path, default=BUILD_DIR)
    start.add_argument("--remote-host", default=REMOTE_HOST)
    start.add_argument("--remote-container", default=REMOTE_CONTAINER)
    start.add_argument("--remote-build-dir", type=Path, default=BUILD_DIR)
    start.add_argument("--zone1-endpoint", default=ENDPOINTS["zone1"])
    start.add_argument("--zone2-endpoint", default=ENDPOINTS["zone2"])
    admin = commands.add_parser("admin", help="run captured radosgw-admin against one lab zone")
    admin.add_argument("zone", choices=ZONES)
    admin.add_argument("args", nargs=argparse.REMAINDER, help="radosgw-admin arguments")
    logs = commands.add_parser("logscollect", help="collect redacted RGW logs, sync status, and ceph status")
    logs.add_argument("--output", type=Path, help="artifact folder (default: build/rgw-repro/logs-TIMESTAMP)")
    return result


def main():
    args = parser().parse_args()
    try:
        if args.command == "setup":
            return setup(args)
        lab = Lab.load(args.config)
        if args.command == "admin":
            lab.check_fsids()
            if not args.args:
                raise LabError("admin requires radosgw-admin arguments")
            command = args.args[1:] if args.args[0] == "--" else args.args
            result = lab.admin(args.zone, *command, check=False)
            sys.stdout.write(lab.redact(result.stdout))
            sys.stderr.write(lab.redact(result.stderr))
            return result.returncode
        # Collect diagnostics even when bootstrap failed or MONs are stopped.
        # A configured FSID mismatch still prevents reading a different lab.
        lab.check_fsids(live=False, complete=False)
        print("Redacted diagnostics: {}".format(lab.collect_logs(args.output)))
        return 0
    except (LabError, subprocess.SubprocessError) as error:
        print("lab: {}".format(error), file=sys.stderr)
        return 1
    except (OSError, ValueError, KeyError, TypeError):
        # Never interpolate arbitrary exception payloads (or command input).
        print("lab: invalid state or filesystem error; inspect private bootstrap.log", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("lab: interrupted; inspect private state/bootstrap.log before retrying", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
